import { Loader2, RefreshCw, Sparkles, Wrench } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { cn } from "@/lib/utils";
import type { RemediationPlan } from "@/lib/types";

import { AiMarker, aiBorder } from "./ai-marker";
import { Markdown, MarkdownInline } from "./markdown";
import { priorityClass } from "./utils";

const sectionLabel = "text-xs font-semibold uppercase tracking-wide text-zinc-500";

type RemediationPlanPanelProps = {
  plan: RemediationPlan;
  generating: boolean;
  error: string | null;
  onGenerate: () => void;
};

export function RemediationPlanPanel({
  plan,
  generating,
  error,
  onGenerate,
}: RemediationPlanPanelProps) {
  const isAi = plan.source === "ai";

  return (
    <Card
      className={cn(
        "rounded-md border bg-white py-0 shadow-sm",
        generating && aiBorder,
      )}
      aria-busy={generating}
    >
      <CardHeader className="border-b p-4">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <Wrench className="size-5 text-emerald-600" />
            <CardTitle>Remediation plan</CardTitle>
            <AiMarker generating={generating} source={plan.source} />
          </div>
          <Button
            variant={isAi ? "outline" : "default"}
            onClick={onGenerate}
            disabled={generating}
          >
            {generating ? (
              <>
                <Loader2 className="size-4 animate-spin" data-icon="inline-start" />
                Generating…
              </>
            ) : isAi ? (
              <>
                <RefreshCw className="size-4" data-icon="inline-start" />
                Regenerate
              </>
            ) : (
              <>
                <Sparkles className="size-4" data-icon="inline-start" />
                Generate AI remediation plan
              </>
            )}
          </Button>
        </div>
        <CardDescription className="mt-1">
          {isAi
            ? "Context-aware plan generated by AI"
            : "Rule-based steps — generate an AI plan for environment-specific guidance"}
        </CardDescription>
        {error ? <p className="mt-2 text-xs text-red-600">{error}</p> : null}
      </CardHeader>
      <CardContent className="space-y-3 p-4" aria-live="polite">
        {plan.steps.map((step, stepIndex) => (
          <div
            key={stepIndex}
            className="rounded-md border border-zinc-200 bg-zinc-50 p-3"
          >
            <div className="flex items-center justify-between gap-3">
              <Badge
                className={cn(
                  "rounded-md px-2 py-1 text-xs font-semibold uppercase",
                  priorityClass[step.priority],
                )}
              >
                {step.priority}
              </Badge>
              {step.addresses.length > 0 ? (
                <span className="truncate text-xs text-zinc-500">
                  Addresses: {step.addresses.join(", ")}
                </span>
              ) : null}
            </div>
            <h3 className="mt-3 text-sm font-semibold">{step.title}</h3>
            {step.summary ? (
              <Markdown content={step.summary} className="mt-1" />
            ) : null}

            {step.steps.length > 0 ? (
              <div className="mt-3">
                <p className={sectionLabel}>Steps</p>
                <ol className="mt-1 list-decimal space-y-1 pl-5 text-sm leading-6 text-zinc-600">
                  {step.steps.map((s, i) => (
                    <li key={i}>
                      <MarkdownInline content={s} />
                    </li>
                  ))}
                </ol>
              </div>
            ) : null}

            {step.commands.length > 0 ? (
              <div className="mt-3">
                <p className={sectionLabel}>Commands</p>
                <div className="mt-1 space-y-2">
                  {step.commands.map((cmd, i) => (
                    <pre
                      key={i}
                      className="overflow-x-auto rounded-md bg-zinc-900 p-3 text-xs text-zinc-100"
                    >
                      <code className="font-mono">{cmd}</code>
                    </pre>
                  ))}
                </div>
              </div>
            ) : null}

            {step.verification ? (
              <div className="mt-3">
                <p className={sectionLabel}>Verify</p>
                <Markdown content={step.verification} className="mt-1" />
              </div>
            ) : null}
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
