import {
  RefreshCw,
  Sparkles,
  Wrench,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { cn } from "@/lib/utils";
import type { RemediationPlan, Scan } from "@/lib/types";

import { AiGenerating } from "./ai-generating";
import { AiMarker, aiBorder } from "./ai-marker";
import { CodeBlock, Markdown, MarkdownInline } from "@/features/scans/detail/markdown/markdown";

const sectionLabel =
  "text-[0.6875rem] font-semibold uppercase tracking-wide text-muted-foreground";

const priorityStyles = {
  now: {
    badge: "bg-red-500 text-white",
  },
  next: {
    badge: "bg-orange-400 text-white",
  },
  later: {
    badge: "bg-amber-400 text-white",
  },
} as const;

type RemediationPlanPanelProps = {
  plan: RemediationPlan;
  scan: Scan;
  generating: boolean;
  error: string | null;
  onGenerate: () => void;
};

export function RemediationPlanPanel({
  plan,
  scan,
  generating,
  error,
  onGenerate,
}: RemediationPlanPanelProps) {
  const isAi = plan.source === "ai";

  return (
    <Card
      className={cn(
        "py-0",
        generating && aiBorder,
      )}
      aria-busy={generating}
    >
      <CardHeader className="border-b p-4">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <Wrench className="size-4 text-emerald-600" />
            <CardTitle className="text-base font-semibold text-foreground">
              Remediation plan
            </CardTitle>
            <AiMarker generating={generating} source={plan.source} />
          </div>
          <Button
            variant={isAi ? "outline" : "default"}
            onClick={onGenerate}
            disabled={generating}
          >
            {generating ? (
              "Generating..."
            ) : isAi ? (
              <>
                <RefreshCw className="size-4" data-icon="inline-start" />
                Regenerate
              </>
            ) : (
              <>
                <Sparkles className="size-4" data-icon="inline-start" />
                Generate AI remediation plan
              </>
            )}
          </Button>
        </div>
        <CardDescription className="mt-1 text-sm text-muted-foreground">
          {isAi
            ? "Context-aware plan generated by AI"
            : "Rule-based steps — generate an AI plan for environment-specific guidance"}
        </CardDescription>
        {error ? <p className="mt-2 text-xs text-red-600">{error}</p> : null}
      </CardHeader>
      <CardContent
        className="p-4"
        aria-live="polite"
        aria-busy={generating}
      >
        <AiGenerating generating={generating} scan={scan} variant="remediation">
          <div className="space-y-4">
            {plan.steps.map((step, stepIndex) => (
              <RemediationStepCard
                key={stepIndex}
                step={step}
              />
            ))}
          </div>
        </AiGenerating>
      </CardContent>
    </Card>
  );
}

type StepCardProps = {
  step: RemediationPlan["steps"][number];
};

function RemediationStepCard({ step }: StepCardProps) {
  const styles = priorityStyles[step.priority];

  return (
    <div className="rounded-md border bg-muted/40 p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0">
          <Badge
            className={cn(
              "mb-4 h-5 rounded-md px-2 text-[0.6875rem] font-bold uppercase leading-none",
              styles.badge,
            )}
          >
            {step.priority}
          </Badge>
          <h3 className="text-sm font-semibold text-foreground">
            {step.title}
          </h3>
        </div>

        {step.addresses.length > 0 ? (
          <span className="max-w-full truncate text-xs text-muted-foreground sm:max-w-[24rem]">
            Addresses: {step.addresses.join(", ")}
          </span>
        ) : null}
      </div>

      {step.summary ? (
        <Markdown
          content={step.summary}
          className="mt-3 text-sm leading-6 text-muted-foreground"
        />
      ) : null}

      {step.steps.length > 0 ? (
        <div className="mt-4">
          <p className={sectionLabel}>Steps</p>
          <ol className="mt-1 list-decimal space-y-1 pl-5 text-sm leading-6 text-muted-foreground">
            {step.steps.map((s, i) => (
              <li key={i}>
                <MarkdownInline content={s} />
              </li>
            ))}
          </ol>
        </div>
      ) : null}

      <div className="mt-4 space-y-4">
        {step.commands.length > 0 ? (
          <div>
            <p className={sectionLabel}>Commands</p>
            <div className="mt-2 space-y-2">
              {step.commands.map((cmd, i) => (
                <CodeBlock key={i} value={cmd} />
              ))}
            </div>
          </div>
        ) : null}

        {step.verification ? (
          <div>
            <p className={sectionLabel}>Verify</p>
            <Markdown
              content={step.verification}
              className="mt-2 text-sm leading-6 text-muted-foreground"
            />
          </div>
        ) : null}
      </div>
    </div>
  );
}
